# Generated by Django 5.0.6 on 2024-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_block_remove_weather_city_delete_city_delete_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='block',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
