# Generated by Django 5.0.7 on 2024-07-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_block_date_time_alter_block_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
